### ISSUE TITLE
Create Branch for LR in Flink

### ISSUE THREAD

**Issue by akunft** [stratosphere/incubator-systemml#12]
@carabolic @FelixNeutatz @fschueler :
- [x] Push to branch flink-lr
- [x] Squash commits in 4 groups: Instructions, Functions, Utils, and SysML
- [x] Remove Tests and their resources
- [x] Check style / optimize Imports on all classes
- [x] Create JIRA issue: Tell what we have done, ask for how to do Tests, mention code duplication and refactoring

**Comment by fschueler** [comment]
I created a branch with reworked commits [here](https://github.com/fschueler/incubator-systemml/commits/rework_commits). Please have a look and see if the grouping makes sense. 
I did not squash the commits but actually reset the tree to the last commit before our changes and grouped them into new commits - that was easier for now, but also makes me the author of everything. 
If you agree on the grouping, we can then squash the commits, which hopefully preserves authorship.

**Comment by aalexandrov** [comment]
@fschueler FYI you can always change the author of selected commits in the history by
1. initiating an interactive rebase, 
2. marking commits with the _stop for amending_ flag, and then
3. doing a `git commit --amend`

**Comment by fschueler** [comment]
I guess then we have to divide the commits between us somehow...

**Comment by akunft** [comment]
:+1: for dividing the commit among you 3

**Comment by akunft** [comment]
I'll do a pass over the commits now and push the branch to the strato repo afterwards

**Comment by akunft** [comment]
So the candidate is in branch https://github.com/stratosphere/incubator-systemml/tree/flink-lr.
I divided the commit among you, I hope you are ok with that.

**Comment by fschueler** [comment]
The corresponding Epic Jira with link to the subtasks can be found [here](https://issues.apache.org/jira/browse/SYSTEMML-636).
