### ISSUE TITLE
Define generic paths in utility class

### ISSUE THREAD

**Issue by akunft** [stratosphere/incubator-systemml#14]
We have to replace the hard coded paths to conf and scripts to runtime dependent paths like we did for resources (`System.getProperty("user.dir")` as base). 

In addition, as we commonly use e.g the resources, conf, scripts folder, we should provide a utils (Paths) class with static fields for these paths.

**Comment by carabolic** [comment]
AFAIK the only places where hard-coded paths are used is in the tests, which will be replaced with proper test that follow the existing SystemML test harness.

Hence the current test need to be deleted anyway and the current test-suite adapted to test Flink execution environment.

Are there places outside our tests where hard-coded paths are used?

**Comment by akunft** [comment]
Not that I'm aware of.
To make the current tests run out of the box, I still suggest to replace the hard coded paths with properties at least.

**Comment by carabolic** [comment]
Fair enough

**Comment by FelixNeutatz** [comment]
The only problem is that Felix uses uncommited test scripts: 
System.getProperty("user.dir") + "/scripts/myScripts/tsmm.dml"

**Comment by fschueler** [comment]
This should be resolved by removing our tests.
