### ISSUE TITLE
Add Flink read/write operations to FlinkExecutionContext

### ISSUE THREAD

**Issue by fschueler** [stratosphere/incubator-systemml#17]
In order to add all functionality to the (CSV)ReblockFLInstructions we need at least `writeDataSetToHDFS(...)` and `toMatrixBlock(...)` methods in FlinkExecutionContext (see `SparkExecutionContext` methods for reference).

These are used in `MatrixObject.readMatrixFromDataSet(...)` which is used by `MatrixObject.aquireRead()`.

**Comment by fschueler** [comment]
- [x] `toMatrixBlock(DataSetObject dso, int rlen, int clen, int brlen, int bclen, long nnz)`
- [x] `toMatrixBlock(DataSet<Tuple2<MatrixIndexes, MatrixBlock>> ds, int rlen, int clen, int brlen, int bclen, long nnz)`
- [x] `writeDataSetToHDFS(DataSetObject dso, String path, OutputInfo oinfo)`

**Comment by FelixNeutatz** [comment]
I implemented writeDataSetToHDFS for you since it is really similar to what I did in writing BinaryBlocks in WriteFLInstruction
