### ISSUE TITLE
Implement other output formats

### ISSUE THREAD

**Issue by FelixNeutatz** [stratosphere/incubator-systemml#19]
Completing:
- [x] org.apache.sysml.runtime.instructions.flink.WriteFLInstruction
- [x] org.apache.sysml.runtime.instructions.flink.functions.ComputeBinaryBlockNnzFunction
- [x] org.apache.sysml.runtime.instructions.flink.functions.ConvertMatrixBlockToIJVLines
- [x] testing it all

**Comment by FelixNeutatz** [comment]
I have two issues with completing WriteFLInstruction:
1. The possibility to set the option to output one single file: 

```
dataset.output(new TextOutputFormat<String>(new org.apache.flink.core.fs.Path(fname)));
MapReduceTool.mergeIntoSingleFile(randFName, fname);
```

The problem is that the merging happens before the execute statement. Therefore there are no files created yet. So the merging fails. We can discuss it on Monday.
1. I also need the Flink specific MatrixObject like Felix implemented 

Apart from this, the following works now:
writing csv, text, mm, binary

**Comment by fschueler** [comment]
I have a branch with some of the IO stuff for flink that can be merged into our staging next week.

Given that we have to keep track of defined sinks I think we can start thinking about what methods to add to the `FlinkExecutionContext` that wraps the `ExecutionEnvironment`. We could define methods there that call `execute()` if necessary. 

In general the whole IO stuff is spread across the `MatrixObject` and `ExecutionContext` and I am not sure about how they decided on what goes where...
