### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by FelixNeutatz** [stratosphere/incubator-systemml#20]
I recognized that some of the classes use tabs for indentation and other spaces. We should use tabs according to the standard :)

**Comment by fschueler** [comment]
The formatting in the whole project is pretty inconsistent in general.
I think we should leave it how it is for the existing classes and for files that we create, decide whether we want tabs or spaces. 
I am a big fan of spaces compared to tabs but we can discuss that ;) 

Or we just go with the inconsistency that exists...

**Comment by FelixNeutatz** [comment]
let's discuss it on Monday :)

**Comment by akunft** [comment]
Lets decide this when we have the PR candidate and then do one pass over all our code.

**Comment by fschueler** [comment]
So it is settled: Tabs it is! :unamused:
