### ISSUE TITLE
Test `hybrid_flink` mode on cluster.

### ISSUE THREAD

**Issue by fschueler** [stratosphere/incubator-systemml#21]
In order to test the Flink instructions, we should run the integration tests with `hybrid_flink` mode in a cluster environment. 
If we only run tests on local machines, Flink instructions will never be executed due to the optimizer.

**Comment by akunft** [comment]
@FelixNeutatz: I think you have most experience with the dima clusters among you.

**Comment by fschueler** [comment]
Successfully tested by @FelixNeutatz

**Comment by fschueler** [comment]
We should do this again with bigger data to ensure that the Flink instuctions are generated.
